version: "3"

services:
  frontend-menudigital:
    build: ./frontend
    container_name: FE-MenuDigital
    working_dir: /appMD-frontend
    tty: true
    stdin_open: true
    ports: 
      - 3000:3000
    restart: always
    volumes:
      - ./frontend/src:appMD-frontend

  backend-menudigital:
    build: ./backend
    container_name: API-MenuDigital
    working_dir: /appMD-backend
    tty: true
    stdin_open: true
    ports:
      - 3001:3001
    depends_on:
      - db
    restart: always
    volumes:
      - ./backend/src:/appMD-backend/src
      - ./.env:/appMD-backend/.env
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - JWT_SECRET=${JWT_SECRET}

  db:
    container_name: DB-MenuDigital
    image: mysql:8.0.32
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}


