export default billProductConsume = [
  { bill_id: 1, product_id: 1 },
  { bill_id: 1, product_id: 2 },
  { bill_id: 1, product_id: 3 },
  { bill_id: 1, product_id: 4 },
  { bill_id: 1, product_id: 5 },
  { bill_id: 2, product_id: 1 },
  { bill_id: 2, product_id: 2 },
  { bill_id: 2, product_id: 3 },
  { bill_id: 2, product_id: 4 },
  { bill_id: 2, product_id: 5 },
  { bill_id: 3, product_id: 1 },
  { bill_id: 3, product_id: 2 },
  { bill_id: 3, product_id: 3 },
  { bill_id: 3, product_id: 4 },
  { bill_id: 3, product_id: 5 },
  { bill_id: 4, product_id: 1 },
  { bill_id: 4, product_id: 2 },
  { bill_id: 4, product_id: 3 },
  { bill_id: 4, product_id: 4 },
  { bill_id: 4, product_id: 5 },
  { bill_id: 5, product_id: 1 },
  { bill_id: 5, product_id: 2 },
  { bill_id: 5, product_id: 3 },
  { bill_id: 5, product_id: 4 },
  { bill_id: 5, product_id: 5 },
];
